### ISSUE TITLE
missed "new" keyword in DrawGeometryHandler

### ISSUE THREAD

**Issue by alsFC** [conterra/mapapps-featureinfo-highlight#1]
thanks to sonarqube ;)

![image](https://user-images.githubusercontent.com/14979356/30699420-faf8abf8-9ee4-11e7-8d03-f51443deefd6.png)

**Comment by matthiasstein** [comment]
Thanks for your advice I have adapted it (https://github.com/conterra/mapapps-featureinfo-highlight/commit/7dae33df44b2b499387d7f930ba93dd7f7571f77).
