### ISSUE TITLE
Wrong feature is highlighted on first click

### ISSUE THREAD

**Issue by dpayk** [conterra/mapapps-featureinfo-highlight#2]
Reproduction
- Click on a place where multiple features are hit.

Expected behavior
- Feature highlight and popup content match

Actual behavior
- Feature highlight and popup content do not match. When switching to next popup content, everything works fine.

**Comment by matthiasstein** [comment]
Fixed in https://github.com/conterra/mapapps-featureinfo-highlight/releases/tag/2.0.1
