### ISSUE TITLE
Bundle 1.0.4 throws an error: "this._drawGeometryHandler is null"

### ISSUE THREAD

**Issue by JoergArnold** [conterra/mapapps-featureinfo-highlight#5]
Hi,

in map.apps V 4.7.2 we using Line 3 Apps together with SDi-Extension V 4.0.3.
When we use the sdi_srschanger-tool the map-context from the app will be "reinitialized" as designed, but in this case bundle stops and the console logs the following error:

TypeError: "this._drawGeometryHandler is null"
(...more lines follow...)

Is it a fault of the dn_featureinfohighlight-bundle Version 1.0.4 (Line 3) ..?
Can you help in this case please?

Best regards,
Jörg Arnold

**Comment by matthiasstein** [comment]
This was fixed in https://github.com/conterra/mapapps-featureinfo-highlight/releases/tag/1.0.5

**Comment by JoergArnold** [comment]
Now it works fine. Thank You.
Best regards,
Jörg Arnold
