### ISSUE TITLE
Highlighting funktioniert nicht bei beschrifteten Layern

### ISSUE THREAD

**Issue by spbnowak** [conterra/mapapps-featureinfo-highlight#6]
in meiner App habe ich einen Map Service mit zwei Layern.
Layer 0 enthält Flurstücken, die mit der Flurstücksnummer beschriftet werden.
Layer 2 enthält Gebäude ohne Beschriftung.
Das Highlighting funktioniert nur bei den Gebäuden.

**Comment by matthiasstein** [comment]
Können Sie Zugriff auf den Dienst gewähren?

**Comment by matthiasstein** [comment]
Gelöst. Es war ein Fehler im Dienst, der über kein Geometry-Attribut verfügte.
